# Generated by Django 5.2 on 2025-04-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'AdminLoginId',
            },
        ),
        migrations.CreateModel(
            name='UserLoginId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'UserLoginId',
            },
        ),
        migrations.CreateModel(
            name='AdminLoggedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.adminloginid')),
            ],
            options={
                'db_table': 'AdminloggedIn',
            },
        ),
        migrations.CreateModel(
            name='UserLoggedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userloginid')),
            ],
            options={
                'db_table': 'UserloggedIn',
            },
        ),
    ]
